Repository PinkyToe69/Web-Crawler, pull requests merged in 2020-12, with the labels that each got.

#33 Modificare si adaugare metode pentru preluarea datelor
  src/WebCrawler/Crawler.java
  src/WebCrawler/Link.java
  src/WebCrawler/Main.java
  src/WebCrawler/Threads.java
  src/WebCrawler/Visited.java
Labels: enhancement

#41 Completare metoda de link-uri vizitate
  src/WebCrawler/Crawler.java
  src/WebCrawler/Threads.java
  src/WebCrawler/Visited.java
  src/WebCrawler/url.txt
Labels: enhancement

#44 Completare functie de constructie sitemap
  src/WebCrawler/BuildSitemap.java
  src/WebCrawler/Main.java
Labels: enhancement

#47 Rezolvare Bug #1
  src/WebCrawler/BuildSitemap.java
  src/WebCrawler/Main.java
  src/WebCrawler/logger.txt
Labels: bug

#51 Issue 50 adaugare documentatie
  sitemap.txt
  src/WebCrawler/BuildSitemap.java
  src/WebCrawler/Crawler.java
  src/WebCrawler/Link.java
  src/WebCrawler/LogManager.java
  src/WebCrawler/Main.java
  src/WebCrawler/Parser.java
  src/WebCrawler/ParserFile.java
  src/WebCrawler/ParserPage.java
  src/WebCrawler/Threads.java
  src/WebCrawler/UserData.java
  src/WebCrawler/Visited.java
  src/WebCrawler/extensii.txt
  src/WebCrawler/logger.txt
  src/logger.txt
Labels: documentation
